import { AcademicClass, AcademicSubject, AcademicChapter, AcademicTopic, AcademicSubTopic, Mcq, Cq } from '@/types';

export const mockClasses: AcademicClass[] = [
  {
    id: 'class-1',
    name: 'class-9',
    level: 'SSC',
    displayName: 'Class 9',
    position: 1,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'class-2',
    name: 'class-10',
    level: 'SSC',
    displayName: 'Class 10',
    position: 2,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'class-3',
    name: 'class-11',
    level: 'HSC',
    displayName: 'Class 11',
    position: 3,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'class-4',
    name: 'o-level',
    level: 'O-Level',
    displayName: 'O Level',
    position: 4,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockSubjects: AcademicSubject[] = [
  {
    id: 'subject-1',
    name: 'physics',
    code: 'PHY',
    displayName: 'Physics',
    position: 1,
    isActive: true,
    classId: 'class-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'subject-2',
    name: 'chemistry',
    code: 'CHEM',
    displayName: 'Chemistry',
    position: 2,
    isActive: true,
    classId: 'class-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'subject-3',
    name: 'mathematics',
    code: 'MATH',
    displayName: 'Mathematics',
    position: 3,
    isActive: true,
    classId: 'class-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'subject-4',
    name: 'biology',
    code: 'BIO',
    displayName: 'Biology',
    position: 4,
    isActive: true,
    classId: 'class-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockChapters: AcademicChapter[] = [
  {
    id: 'chapter-1',
    name: 'motion',
    displayName: 'Motion',
    position: 1,
    isActive: true,
    subjectId: 'subject-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'chapter-2',
    name: 'force',
    displayName: 'Force and Laws of Motion',
    position: 2,
    isActive: true,
    subjectId: 'subject-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'chapter-3',
    name: 'atoms-molecules',
    displayName: 'Atoms and Molecules',
    position: 1,
    isActive: true,
    subjectId: 'subject-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'chapter-4',
    name: 'number-systems',
    displayName: 'Number Systems',
    position: 1,
    isActive: true,
    subjectId: 'subject-3',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockTopics: AcademicTopic[] = [
  {
    id: 'topic-1',
    name: 'distance-displacement',
    displayName: 'Distance and Displacement',
    position: 1,
    isActive: true,
    chapterId: 'chapter-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'topic-2',
    name: 'speed-velocity',
    displayName: 'Speed and Velocity',
    position: 2,
    isActive: true,
    chapterId: 'chapter-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'topic-3',
    name: 'acceleration',
    displayName: 'Acceleration',
    position: 3,
    isActive: true,
    chapterId: 'chapter-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'topic-4',
    name: 'newtons-laws',
    displayName: "Newton's Laws of Motion",
    position: 1,
    isActive: true,
    chapterId: 'chapter-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockSubTopics: AcademicSubTopic[] = [
  {
    id: 'subtopic-1',
    name: 'scalar-quantities',
    displayName: 'Scalar Quantities',
    position: 1,
    isActive: true,
    topicId: 'topic-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'subtopic-2',
    name: 'vector-quantities',
    displayName: 'Vector Quantities',
    position: 2,
    isActive: true,
    topicId: 'topic-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'subtopic-3',
    name: 'uniform-velocity',
    displayName: 'Uniform Velocity',
    position: 1,
    isActive: true,
    topicId: 'topic-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockMcqs: Mcq[] = [
  {
    id: 'mcq-1',
    question: 'What is the SI unit of velocity?',
    options: ['m/s', 'km/h', 'm/s²', 'N'],
    answer: 'm/s',
    explanation: 'Velocity is measured in meters per second (m/s) in the SI system.',
    difficulty: 'EASY',
    marks: 1,
    subjectId: 'subject-1',
    chapterId: 'chapter-1',
    topicId: 'topic-2',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'mcq-2',
    question: 'Which of the following is a vector quantity?',
    options: ['Speed', 'Distance', 'Displacement', 'Time'],
    answer: 'Displacement',
    explanation: 'Displacement has both magnitude and direction, making it a vector quantity.',
    difficulty: 'EASY',
    marks: 1,
    subjectId: 'subject-1',
    chapterId: 'chapter-1',
    topicId: 'topic-1',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'mcq-3',
    question: 'What is the acceleration due to gravity on Earth?',
    options: ['9.8 m/s²', '10 m/s', '9.8 m/s', '10 m/s²'],
    answer: '9.8 m/s²',
    explanation: 'The standard acceleration due to gravity on Earth is approximately 9.8 m/s².',
    difficulty: 'MEDIUM',
    marks: 1,
    subjectId: 'subject-1',
    chapterId: 'chapter-1',
    topicId: 'topic-3',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'mcq-4',
    question: "According to Newton's first law, an object at rest will:",
    options: ['Always remain at rest', 'Start moving slowly', 'Remain at rest unless acted upon by an external force', 'Accelerate'],
    answer: 'Remain at rest unless acted upon by an external force',
    difficulty: 'MEDIUM',
    marks: 1,
    subjectId: 'subject-1',
    chapterId: 'chapter-2',
    topicId: 'topic-4',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockCqs: Cq[] = [
  {
    id: 'cq-1',
    context: 'A car travels from city A to city B, covering a distance of 100 km in 2 hours. The car then returns to city A taking the same route in 2.5 hours.',
    questionA: 'Define displacement.',
    questionB: 'Calculate the average speed of the car for the entire journey.',
    questionC: 'Calculate the average velocity of the car for the entire journey.',
    questionD: 'Explain why the average velocity is different from the average speed in this case.',
    marks: 10,
    subjectId: 'subject-1',
    chapterId: 'chapter-1',
    topicId: 'topic-1',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'cq-2',
    context: 'A ball is thrown vertically upward with an initial velocity of 20 m/s. (Take g = 10 m/s²)',
    questionA: 'What is meant by acceleration?',
    questionB: 'Calculate the time taken by the ball to reach maximum height.',
    questionC: 'Find the maximum height reached by the ball.',
    questionD: 'Analyze the motion of the ball during its upward and downward journey.',
    marks: 10,
    subjectId: 'subject-1',
    chapterId: 'chapter-1',
    topicId: 'topic-3',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

// Helper functions
export const getClassById = (id: string) => mockClasses.find(c => c.id === id);
export const getSubjectById = (id: string) => mockSubjects.find(s => s.id === id);
export const getChapterById = (id: string) => mockChapters.find(c => c.id === id);
export const getTopicById = (id: string) => mockTopics.find(t => t.id === id);
export const getSubTopicById = (id: string) => mockSubTopics.find(s => s.id === id);

export const getSubjectsByClass = (classId: string) => mockSubjects.filter(s => s.classId === classId);
export const getChaptersBySubject = (subjectId: string) => mockChapters.filter(c => c.subjectId === subjectId);
export const getTopicsByChapter = (chapterId: string) => mockTopics.filter(t => t.chapterId === chapterId);
export const getSubTopicsByTopic = (topicId: string) => mockSubTopics.filter(s => s.topicId === topicId);
