import { Tenant, User, Session } from '@/types';

export const mockTenants: Tenant[] = [
  {
    id: '1',
    name: 'ABC High School',
    slug: 'abc-high-school',
    description: 'A premier high school offering quality education since 1990.',
    type: 'SCHOOL',
    email: 'admin@abchigh.edu.bd',
    phone: '+880-1711-000001',
    address: 'House 12, Road 5, Dhanmondi',
    city: 'Dhaka',
    state: 'Dhaka Division',
    country: 'BD',
    postalCode: '1205',
    subdomain: 'abc-high',
    tenantDatabaseName: 'db_abc_high_school',
    tenantDatabaseStatus: 'ACTIVE',
    subscriptionTier: 'PRO',
    subscriptionStatus: 'ACTIVE',
    studentCount: 1250,
    teacherCount: 45,
    examCount: 120,
    storageUsedMB: 450,
    studentLimit: 2000,
    teacherLimit: 100,
    examLimit: 500,
    storageLimit: 1000,
    monthlyPriceBDT: 5000,
    yearlyPriceBDT: 50000,
    customDomainVerified: false,
    isActive: true,
    isSuspended: false,
    currentAcademicYear: '2024',
    features: { smsNotifications: true, parentPortal: true },
    metadata: { schoolCode: 'ABC123', affiliation: 'NCTB' },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    name: 'XYZ Coaching Center',
    slug: 'xyz-coaching',
    description: 'Premier coaching center for SSC/HSC preparation.',
    type: 'COACHING_CENTER',
    email: 'info@xyzcoaching.com',
    phone: '+880-1811-000002',
    address: 'Station Road, GEC Circle',
    city: 'Chittagong',
    state: 'Chittagong Division',
    country: 'BD',
    postalCode: '4000',
    subdomain: 'xyz-coaching',
    tenantDatabaseName: 'db_xyz_coaching',
    tenantDatabaseStatus: 'ACTIVE',
    subscriptionTier: 'STARTER',
    subscriptionStatus: 'TRIAL',
    trialEndsAt: new Date('2024-03-01'),
    studentCount: 320,
    teacherCount: 12,
    examCount: 45,
    storageUsedMB: 120,
    studentLimit: 500,
    teacherLimit: 20,
    examLimit: 100,
    storageLimit: 500,
    monthlyPriceBDT: 2000,
    yearlyPriceBDT: 20000,
    customDomainVerified: false,
    isActive: true,
    isSuspended: false,
    features: { smsNotifications: true, parentPortal: false },
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: '3',
    name: "John's Math Academy",
    slug: 'johns-math',
    description: 'Personalized math tutoring for all levels.',
    type: 'INDIVIDUAL',
    email: 'john@mathacademy.com',
    phone: '+880-1911-000003',
    city: 'Sylhet',
    state: 'Sylhet Division',
    country: 'BD',
    subdomain: 'johns-math',
    tenantDatabaseName: 'db_johns_math',
    tenantDatabaseStatus: 'PROVISIONING',
    subscriptionTier: 'FREE',
    subscriptionStatus: 'TRIAL',
    trialEndsAt: new Date('2024-03-10'),
    studentCount: 45,
    teacherCount: 1,
    examCount: 10,
    storageUsedMB: 25,
    studentLimit: 50,
    teacherLimit: 2,
    examLimit: 20,
    storageLimit: 100,
    monthlyPriceBDT: 0,
    yearlyPriceBDT: 0,
    customDomainVerified: false,
    isActive: true,
    isSuspended: false,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '4',
    name: 'National University',
    slug: 'national-uni',
    description: 'One of the largest universities in Bangladesh, offering diverse programs.',
    type: 'UNIVERSITY',
    email: 'registrar@nu.edu.bd',
    phone: '+880-2-7912345',
    address: 'Gazipur',
    city: 'Gazipur',
    state: 'Dhaka Division',
    country: 'BD',
    postalCode: '1704',
    subdomain: 'national-uni',
    customDomain: 'exams.nationaluni.edu.bd',
    customDomainVerified: true,
    tenantDatabaseName: 'db_national_uni',
    tenantDatabaseStatus: 'ACTIVE',
    subscriptionTier: 'ENTERPRISE',
    subscriptionStatus: 'ACTIVE',
    subscriptionEndsAt: new Date('2025-12-31'),
    studentCount: 15000,
    teacherCount: 450,
    examCount: 2500,
    storageUsedMB: 8500,
    studentLimit: 20000,
    teacherLimit: 1000,
    examLimit: 5000,
    storageLimit: 10000,
    monthlyPriceBDT: 25000,
    yearlyPriceBDT: 250000,
    isActive: true,
    isSuspended: false,
    currentAcademicYear: '2024',
    features: { smsNotifications: true, parentPortal: true, apiAccess: true },
    metadata: { universityCode: 'NU001', accreditation: 'UGC' },
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '5',
    name: 'Tech Training Hub',
    slug: 'tech-training',
    description: 'Professional IT training and certification programs.',
    type: 'TRAINING_CENTER',
    email: 'contact@techtraininghub.com',
    phone: '+880-1611-000005',
    address: 'Mohakhali DOHS',
    city: 'Dhaka',
    state: 'Dhaka Division',
    country: 'BD',
    postalCode: '1206',
    subdomain: 'tech-training',
    tenantDatabaseName: 'db_tech_training',
    tenantDatabaseStatus: 'ACTIVE',
    subscriptionTier: 'PRO',
    subscriptionStatus: 'PAST_DUE',
    subscriptionEndsAt: new Date('2024-02-15'),
    studentCount: 850,
    teacherCount: 25,
    examCount: 200,
    storageUsedMB: 680,
    studentLimit: 1000,
    teacherLimit: 50,
    examLimit: 300,
    storageLimit: 1000,
    monthlyPriceBDT: 5000,
    yearlyPriceBDT: 50000,
    customDomainVerified: false,
    isActive: true,
    isSuspended: false,
    features: { smsNotifications: true, parentPortal: false },
    createdAt: new Date('2023-09-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '6',
    name: 'Sunrise Academy',
    slug: 'sunrise-academy',
    description: 'English medium school following Cambridge curriculum.',
    type: 'SCHOOL',
    email: 'principal@sunriseacademy.edu.bd',
    phone: '+880-1511-000006',
    address: 'Gulshan-2',
    city: 'Dhaka',
    state: 'Dhaka Division',
    country: 'BD',
    postalCode: '1212',
    subdomain: 'sunrise-academy',
    tenantDatabaseName: 'db_sunrise_academy',
    tenantDatabaseStatus: 'ACTIVE',
    subscriptionTier: 'ENTERPRISE',
    subscriptionStatus: 'ACTIVE',
    studentCount: 2200,
    teacherCount: 120,
    examCount: 450,
    storageUsedMB: 1800,
    studentLimit: 3000,
    teacherLimit: 200,
    examLimit: 1000,
    storageLimit: 5000,
    monthlyPriceBDT: 15000,
    yearlyPriceBDT: 150000,
    customDomain: 'portal.sunriseacademy.edu.bd',
    customDomainVerified: true,
    isActive: true,
    isSuspended: false,
    currentAcademicYear: '2024',
    features: { smsNotifications: true, parentPortal: true, apiAccess: true },
    metadata: { schoolCode: 'SRS456', affiliation: 'Cambridge' },
    createdAt: new Date('2023-03-01'),
    updatedAt: new Date('2024-01-30'),
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@shikhonary.com',
    emailVerified: true,
    role: 'SUPER_ADMIN',
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'John Teacher',
    email: 'john@abchigh.edu.bd',
    emailVerified: true,
    tenantId: '1',
    role: 'TEACHER',
    isActive: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    name: 'Sarah Ahmed',
    email: 'sarah.ahmed@gmail.com',
    emailVerified: true,
    role: 'TENANT_ADMIN',
    isActive: true,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '4',
    name: 'Mohammad Hasan',
    email: 'hasan@techtraining.com',
    emailVerified: true,
    tenantId: '5',
    role: 'TENANT_ADMIN',
    isActive: true,
    createdAt: new Date('2023-09-15'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    name: 'Fatima Begum',
    email: 'fatima.begum@sunrise.edu.bd',
    emailVerified: true,
    role: 'TEACHER',
    isActive: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '6',
    name: 'Karim Rahman',
    email: 'karim.rahman@outlook.com',
    emailVerified: false,
    role: 'STUDENT',
    isActive: true,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '7',
    name: 'Rashida Khan',
    email: 'rashida@xyzcoaching.com',
    emailVerified: true,
    role: 'TENANT_ADMIN',
    isActive: true,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: '8',
    name: 'Abdullah Mahmud',
    email: 'abdullah.m@gmail.com',
    emailVerified: true,
    role: 'PARENT',
    isActive: true,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
];

export const mockSessions: Session[] = [
  {
    id: '1',
    expiresAt: new Date('2024-03-01'),
    token: 'mock-token-1',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
    ipAddress: '192.168.1.1',
    userAgent: 'Chrome/120.0.0.0',
    userId: '1',
  },
];

export const getTenantById = (id: string): Tenant | undefined => {
  return mockTenants.find(t => t.id === id);
};
