import { Tenant, User, Session } from '@/types';

export const mockTenants: Tenant[] = [
  {
    id: '1',
    name: 'ABC High School',
    slug: 'abc-high-school',
    description: 'A premier high school offering quality education since 1990.',
    type: 'SCHOOL',
    email: 'admin@abchigh.edu.bd',
    phone: '+880-1711-000001',
    address: 'House 12, Road 5, Dhanmondi',
    city: 'Dhaka',
    state: 'Dhaka Division',
    country: 'BD',
    postalCode: '1205',
    subdomain: 'abc-high',
    tenantDatabaseName: 'db_abc_high_school',
    tenantDatabaseStatus: 'ACTIVE',
    subscriptionTier: 'PRO',
    subscriptionStatus: 'ACTIVE',
    studentCount: 1250,
    teacherCount: 45,
    examCount: 120,
    storageUsedMB: 450,
    studentLimit: 2000,
    teacherLimit: 100,
    examLimit: 500,
    storageLimit: 1000,
    monthlyPriceBDT: 5000,
    yearlyPriceBDT: 50000,
    customDomainVerified: false,
    isActive: true,
    isSuspended: false,
    currentAcademicYear: '2024',
    features: { smsNotifications: true, parentPortal: true },
    metadata: { schoolCode: 'ABC123', affiliation: 'NCTB' },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    name: 'XYZ Coaching Center',
    slug: 'xyz-coaching',
    description: 'Premier coaching center for SSC/HSC preparation.',
    type: 'COACHING_CENTER',
    email: 'info@xyzcoaching.com',
    phone: '+880-1811-000002',
    address: 'Station Road, GEC Circle',
    city: 'Chittagong',
    state: 'Chittagong Division',
    country: 'BD',
    postalCode: '4000',
    subdomain: 'xyz-coaching',
    tenantDatabaseName: 'db_xyz_coaching',
    tenantDatabaseStatus: 'ACTIVE',
    subscriptionTier: 'STARTER',
    subscriptionStatus: 'TRIAL',
    trialEndsAt: new Date('2024-03-01'),
    studentCount: 320,
    teacherCount: 12,
    examCount: 45,
    storageUsedMB: 120,
    studentLimit: 500,
    teacherLimit: 20,
    examLimit: 100,
    storageLimit: 500,
    monthlyPriceBDT: 2000,
    yearlyPriceBDT: 20000,
    customDomainVerified: false,
    isActive: true,
    isSuspended: false,
    features: { smsNotifications: true, parentPortal: false },
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: '3',
    name: "John's Math Academy",
    slug: 'johns-math',
    description: 'Personalized math tutoring for all levels.',
    type: 'INDIVIDUAL',
    email: 'john@mathacademy.com',
    phone: '+880-1911-000003',
    city: 'Sylhet',
    state: 'Sylhet Division',
    country: 'BD',
    subdomain: 'johns-math',
    tenantDatabaseName: 'db_johns_math',
    tenantDatabaseStatus: 'PROVISIONING',
    subscriptionTier: 'FREE',
    subscriptionStatus: 'TRIAL',
    trialEndsAt: new Date('2024-03-10'),
    studentCount: 45,
    teacherCount: 1,
    examCount: 10,
    storageUsedMB: 25,
    studentLimit: 50,
    teacherLimit: 2,
    examLimit: 20,
    storageLimit: 100,
    monthlyPriceBDT: 0,
    yearlyPriceBDT: 0,
    customDomainVerified: false,
    isActive: true,
    isSuspended: false,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '4',
    name: 'National University',
    slug: 'national-uni',
    description: 'One of the largest universities in Bangladesh, offering diverse programs.',
    type: 'UNIVERSITY',
    email: 'registrar@nu.edu.bd',
    phone: '+880-2-7912345',
    address: 'Gazipur',
    city: 'Gazipur',
    state: 'Dhaka Division',
    country: 'BD',
    postalCode: '1704',
    subdomain: 'national-uni',
    customDomain: 'exams.nationaluni.edu.bd',
    customDomainVerified: true,
    tenantDatabaseName: 'db_national_uni',
    tenantDatabaseStatus: 'ACTIVE',
    subscriptionTier: 'ENTERPRISE',
    subscriptionStatus: 'ACTIVE',
    subscriptionEndsAt: new Date('2025-12-31'),
    studentCount: 15000,
    teacherCount: 450,
    examCount: 2500,
    storageUsedMB: 8500,
    studentLimit: 20000,
    teacherLimit: 1000,
    examLimit: 5000,
    storageLimit: 10000,
    monthlyPriceBDT: 25000,
    yearlyPriceBDT: 250000,
    isActive: true,
    isSuspended: false,
    currentAcademicYear: '2024',
    features: { smsNotifications: true, parentPortal: true, apiAccess: true },
    metadata: { universityCode: 'NU001', accreditation: 'UGC' },
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '5',
    name: 'Tech Training Hub',
    slug: 'tech-training',
    description: 'Professional IT training and certification programs.',
    type: 'TRAINING_CENTER',
    email: 'contact@techtraininghub.com',
    phone: '+880-1611-000005',
    address: 'Mohakhali DOHS',
    city: 'Dhaka',
    state: 'Dhaka Division',
    country: 'BD',
    postalCode: '1206',
    subdomain: 'tech-training',
    tenantDatabaseName: 'db_tech_training',
    tenantDatabaseStatus: 'ACTIVE',
    subscriptionTier: 'PRO',
    subscriptionStatus: 'PAST_DUE',
    subscriptionEndsAt: new Date('2024-02-15'),
    studentCount: 850,
    teacherCount: 25,
    examCount: 200,
    storageUsedMB: 680,
    studentLimit: 1000,
    teacherLimit: 50,
    examLimit: 300,
    storageLimit: 1000,
    monthlyPriceBDT: 5000,
    yearlyPriceBDT: 50000,
    customDomainVerified: false,
    isActive: true,
    isSuspended: false,
    features: { smsNotifications: true, parentPortal: false },
    createdAt: new Date('2023-09-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '6',
    name: 'Sunrise Academy',
    slug: 'sunrise-academy',
    description: 'English medium school following Cambridge curriculum.',
    type: 'SCHOOL',
    email: 'principal@sunriseacademy.edu.bd',
    phone: '+880-1511-000006',
    address: 'Gulshan-2',
    city: 'Dhaka',
    state: 'Dhaka Division',
    country: 'BD',
    postalCode: '1212',
    subdomain: 'sunrise-academy',
    tenantDatabaseName: 'db_sunrise_academy',
    tenantDatabaseStatus: 'ACTIVE',
    subscriptionTier: 'ENTERPRISE',
    subscriptionStatus: 'ACTIVE',
    studentCount: 2200,
    teacherCount: 120,
    examCount: 450,
    storageUsedMB: 1800,
    studentLimit: 3000,
    teacherLimit: 200,
    examLimit: 1000,
    storageLimit: 5000,
    monthlyPriceBDT: 15000,
    yearlyPriceBDT: 150000,
    customDomain: 'portal.sunriseacademy.edu.bd',
    customDomainVerified: true,
    isActive: true,
    isSuspended: false,
    currentAcademicYear: '2024',
    features: { smsNotifications: true, parentPortal: true, apiAccess: true },
    metadata: { schoolCode: 'SRS456', affiliation: 'Cambridge' },
    createdAt: new Date('2023-03-01'),
    updatedAt: new Date('2024-01-30'),
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@shikhonary.com',
    emailVerified: true,
    role: 'SUPER_ADMIN',
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'John Teacher',
    email: 'john@abchigh.edu.bd',
    emailVerified: true,
    tenantId: '1',
    role: 'TEACHER',
    isActive: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    name: 'Sarah Ahmed',
    email: 'sarah.ahmed@gmail.com',
    emailVerified: true,
    role: 'TENANT_ADMIN',
    isActive: true,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '4',
    name: 'Mohammad Hasan',
    email: 'hasan@techtraining.com',
    emailVerified: true,
    tenantId: '5',
    role: 'TENANT_ADMIN',
    isActive: true,
    createdAt: new Date('2023-09-15'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    name: 'Fatima Begum',
    email: 'fatima.begum@sunrise.edu.bd',
    emailVerified: true,
    role: 'TEACHER',
    isActive: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '6',
    name: 'Karim Rahman',
    email: 'karim.rahman@outlook.com',
    emailVerified: false,
    role: 'STUDENT',
    isActive: true,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '7',
    name: 'Rashida Khan',
    email: 'rashida@xyzcoaching.com',
    emailVerified: true,
    role: 'TENANT_ADMIN',
    isActive: true,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: '8',
    name: 'Abdullah Mahmud',
    email: 'abdullah.m@gmail.com',
    emailVerified: true,
    role: 'PARENT',
    isActive: true,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
];

export const mockSessions: Session[] = [
  {
    id: '1',
    expiresAt: new Date('2024-03-01'),
    token: 'mock-token-1',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
    ipAddress: '192.168.1.1',
    userAgent: 'Chrome/120.0.0.0',
    userId: '1',
  },
];

export const getTenantById = (id: string): Tenant | undefined => {
  return mockTenants.find(t => t.id === id);
};

// ── Mock Subscriptions ─────────────────────────────────────────────────────

export interface MockSubscription {
  id: string;
  tenant_id: string;
  tenant_name: string;
  tier: string;
  status: 'trial' | 'active' | 'past_due' | 'canceled' | 'expired';
  current_period_start: string;
  current_period_end: string;
  price_per_month: number;
  price_per_year: number | null;
  currency: string;
  billing_cycle: string;
  payment_provider: string | null;
  cancel_at_period_end: boolean;
  cancel_reason: string | null;
  canceled_at: string | null;
  external_id: string | null;
  created_at: string;
  updated_at: string;
}

export const mockSubscriptions: MockSubscription[] = [
  {
    id: 'sub_001',
    tenant_id: '4',
    tenant_name: 'National University',
    tier: 'ENTERPRISE',
    status: 'active',
    current_period_start: '2025-01-01',
    current_period_end: '2025-12-31',
    price_per_month: 25000,
    price_per_year: 250000,
    currency: 'BDT',
    billing_cycle: 'yearly',
    payment_provider: 'stripe',
    cancel_at_period_end: false,
    cancel_reason: null,
    canceled_at: null,
    external_id: 'sub_stripe_enterprise_001',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'sub_002',
    tenant_id: '1',
    tenant_name: 'ABC High School',
    tier: 'PRO',
    status: 'active',
    current_period_start: '2025-02-01',
    current_period_end: '2025-03-01',
    price_per_month: 5000,
    price_per_year: 50000,
    currency: 'BDT',
    billing_cycle: 'monthly',
    payment_provider: 'bkash',
    cancel_at_period_end: false,
    cancel_reason: null,
    canceled_at: null,
    external_id: 'bkash_pro_abc_001',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2025-02-01T00:00:00Z',
  },
  {
    id: 'sub_003',
    tenant_id: '2',
    tenant_name: 'XYZ Coaching Center',
    tier: 'STARTER',
    status: 'trial',
    current_period_start: '2025-02-01',
    current_period_end: '2025-03-01',
    price_per_month: 2000,
    price_per_year: 20000,
    currency: 'BDT',
    billing_cycle: 'monthly',
    payment_provider: null,
    cancel_at_period_end: false,
    cancel_reason: null,
    canceled_at: null,
    external_id: null,
    created_at: '2025-02-01T00:00:00Z',
    updated_at: '2025-02-01T00:00:00Z',
  },
  {
    id: 'sub_004',
    tenant_id: '3',
    tenant_name: "John's Math Academy",
    tier: 'FREE',
    status: 'trial',
    current_period_start: '2025-02-10',
    current_period_end: '2025-03-10',
    price_per_month: 0,
    price_per_year: 0,
    currency: 'BDT',
    billing_cycle: 'monthly',
    payment_provider: null,
    cancel_at_period_end: false,
    cancel_reason: null,
    canceled_at: null,
    external_id: null,
    created_at: '2025-02-10T00:00:00Z',
    updated_at: '2025-02-10T00:00:00Z',
  },
  {
    id: 'sub_005',
    tenant_id: '5',
    tenant_name: 'Dhaka Training Institute',
    tier: 'PRO',
    status: 'past_due',
    current_period_start: '2025-01-15',
    current_period_end: '2025-02-15',
    price_per_month: 5000,
    price_per_year: null,
    currency: 'BDT',
    billing_cycle: 'monthly',
    payment_provider: 'nagad',
    cancel_at_period_end: false,
    cancel_reason: null,
    canceled_at: null,
    external_id: 'nagad_pro_dti_001',
    created_at: '2024-06-15T00:00:00Z',
    updated_at: '2025-02-15T00:00:00Z',
  },
  {
    id: 'sub_006',
    tenant_id: '6',
    tenant_name: 'Sylhet International School',
    tier: 'STARTER',
    status: 'canceled',
    current_period_start: '2024-11-01',
    current_period_end: '2025-02-01',
    price_per_month: 2000,
    price_per_year: null,
    currency: 'BDT',
    billing_cycle: 'monthly',
    payment_provider: 'bkash',
    cancel_at_period_end: true,
    cancel_reason: 'Switching to a different platform',
    canceled_at: '2025-01-20T00:00:00Z',
    external_id: 'bkash_starter_sis_001',
    created_at: '2024-11-01T00:00:00Z',
    updated_at: '2025-01-20T00:00:00Z',
  },
  {
    id: 'sub_007',
    tenant_id: '7',
    tenant_name: 'Rajshahi Science College',
    tier: 'PRO',
    status: 'expired',
    current_period_start: '2024-08-01',
    current_period_end: '2025-01-01',
    price_per_month: 5000,
    price_per_year: 50000,
    currency: 'BDT',
    billing_cycle: 'yearly',
    payment_provider: 'stripe',
    cancel_at_period_end: false,
    cancel_reason: null,
    canceled_at: null,
    external_id: 'sub_stripe_pro_rsc_001',
    created_at: '2024-08-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'sub_008',
    tenant_id: '8',
    tenant_name: 'Khulna Medical College',
    tier: 'ENTERPRISE',
    status: 'active',
    current_period_start: '2025-01-01',
    current_period_end: '2026-01-01',
    price_per_month: 25000,
    price_per_year: 250000,
    currency: 'BDT',
    billing_cycle: 'yearly',
    payment_provider: 'stripe',
    cancel_at_period_end: false,
    cancel_reason: null,
    canceled_at: null,
    external_id: 'sub_stripe_enterprise_002',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
];

export const getSubscriptionById = (id: string): MockSubscription | undefined => {
  return mockSubscriptions.find(s => s.id === id);
};
