import { PaperQuestion, PaperSettings, HeaderStyles, MarginSettings } from '@/components/tenant/question-paper/types';

const defaultHeaderStyles: HeaderStyles = {
  institutionName: { fontSize: 20, fontFamily: 'SolaimanLipi', textAlign: 'center' },
  className: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'center' },
  subjectName: { fontSize: 16, fontFamily: 'SolaimanLipi', textAlign: 'center' },
  chapterName: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'center' },
  setCode: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'center' },
  examName: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'center' },
  time: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
  totalMarks: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'right' },
  instructions: { fontSize: 12, fontFamily: 'SolaimanLipi', textAlign: 'left' },
};

const defaultMargins: MarginSettings = {
  top: 20,
  bottom: 20,
  left: 15,
  right: 15,
};

export const defaultPaperSettings: PaperSettings = {
  institutionName: 'Basic Education Care',
  showClassName: true,
  showSubjectName: true,
  showChapterName: true,
  showSetCode: true,
  setCode: 'ক',
  showExamName: true,
  examName: 'Model Test',
  showInstructions: true,
  instructions: 'প্রতিটি প্রশ্নের সঠিক উত্তর শুধু একটি। উত্তরপত্রে প্রশ্নের ক্রমিক নম্বরের বিপরীতে প্রদত্ত বর্ণসমূহলিত বৃত্ত সমূহ হতে সঠিক উত্তরের বৃত্তটি বল পয়েন্ট কলম দ্বারা সম্পূর্ণ ভরাট করো। প্রতিটি প্রশ্নের মান ১।',
  showNoMarkingNote: true,
  showTime: true,
  time: '৩০ মিনিট',
  showTotalMarks: true,
  totalMarks: 20,
  className: 'নবম/দশম',
  subjectName: 'বাংলা ১ম পত্র',
  chapterName: 'গদ্য ১ - সুভা',
  
  headerStyles: defaultHeaderStyles,
  
  // Page layout
  paperSize: 'A4',
  paperOrientation: 'portrait',
  margins: defaultMargins,
  columns: 2,
  showColumnDivider: true,
  
  // Typography
  optionStyle: 'parentheses',
  fontFamily: 'SolaimanLipi',
  fontSize: 14,
  fontWeight: 'normal',
  lineHeight: 1.1,
  textAlign: 'left',
  
  // Tools
  detectDuplicates: false,
  enableShuffle: false,
  shuffleQuestions: false,
  shuffleOptions: false,
  
  // Branding
  showAddress: false,
  address: '',
  showWatermark: false,
  watermark: '',
};

export const mockPaperQuestions: PaperQuestion[] = [
  {
    id: 'pq-1',
    number: 1,
    question: "'সুভা' গল্পে উল্লিখিত 'গভীর নিস্তব্ধ পাতালপুরী' কেমন?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'বিস্তীর্ণপুর্ণ' },
      { label: 'খ', text: 'তরুচ্ছায়াময়' },
      { label: 'গ', text: 'মণিদীপ্ত' },
      { label: 'ঘ', text: 'বিষাদশায়ী' },
    ],
    correctAnswer: 'গ',
    type: 'single',
  },
  {
    id: 'pq-2',
    number: 2,
    question: "'সুভা' গল্পে 'চির নিস্তব্ধ হৃদয় উপকূল' বলতে কী বোঝানো হয়েছে?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'শান্ত হৃদয়' },
      { label: 'খ', text: 'কূলের সদৃশ্য' },
      { label: 'গ', text: 'হৃদয়ের কিনার' },
      { label: 'ঘ', text: 'হৃদয়ের মধ্য' },
    ],
    correctAnswer: 'গ',
    type: 'single',
  },
  {
    id: 'pq-3',
    number: 3,
    question: 'সরশেষে অসহায় সুভা আত্মসমর্পণ করেছে কার কাছে?',
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'ধরণির কাছে' },
      { label: 'খ', text: 'গাভী দুটির কাছে' },
      { label: 'গ', text: 'মায়ের কাছে' },
      { label: 'ঘ', text: 'বাণীকণ্ঠের কাছে' },
    ],
    correctAnswer: 'ঘ',
    type: 'single',
  },
  {
    id: 'pq-4',
    number: 4,
    question: "সুভার সঙ্গীদের মধ্যে তায়াবিশিষ্ট জীব বলা হয়েছে কাকে?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'সর্বশী' },
      { label: 'খ', text: 'পাঙ্গুলি' },
      { label: 'গ', text: 'প্রতাপ' },
      { label: 'ঘ', text: 'বাণীকণ্ঠ' },
    ],
    correctAnswer: 'গ',
    type: 'single',
  },
  {
    id: 'pq-5',
    number: 5,
    question: "সুভা বিধাতার কাছে অলৌকিক ক্ষমতা প্রার্থনা করত-\ni. প্রতাপের মনোযোগ আকর্ষণ করার জন্য\nii. মায়ের বিরম্বনি দূর করার জন্য",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'i' },
      { label: 'খ', text: 'ii' },
      { label: 'গ', text: 'i ও ii' },
      { label: 'ঘ', text: 'কোনোটিই নয়' },
    ],
    correctAnswer: 'গ',
    type: 'statement',
    statements: [
      'প্রতাপের মনোযোগ আকর্ষণ করার জন্য',
      'মায়ের বিরম্বনি দূর করার জন্য',
    ],
  },
  {
    id: 'pq-6',
    number: 6,
    question: "'নীলমণি' কবিতায় কোন চরিত্র?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'নীলমণি' },
      { label: 'খ', text: 'হরিহর রায়' },
      { label: 'গ', text: 'প্রতাপ রায়' },
      { label: 'ঘ', text: 'বাণীকণ্ঠ' },
    ],
    correctAnswer: 'ক',
    type: 'single',
  },
  {
    id: 'pq-7',
    number: 7,
    question: "'তুমি আমাকে মাইতে দিয়ো না, মা।'- সুভার এ কথা কী প্রকাশ পেয়েছে?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'আকুলতা' },
      { label: 'খ', text: 'অভিব্রত' },
      { label: 'গ', text: 'প্রার্থনা' },
      { label: 'ঘ', text: 'চঞ্চলতা' },
    ],
    correctAnswer: 'ক',
    type: 'single',
  },
  {
    id: 'pq-8',
    number: 8,
    question: "সুভা সাধারণের দৃষ্টিপথ থেকে নিজেকে গোপন রাখতে সচেষ্ট ছিল কেন?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'পিতামাতা নীর হৃদয়তার তলে' },
      { label: 'খ', text: 'বিধাতার অভিশাপরূপে মনে করে' },
      { label: 'গ', text: 'তাদেরকে এক-ধরে করতে চায় বলে' },
      { label: 'ঘ', text: 'সে মায়ের গর্বকল্প- এ কথা মনে করে' },
    ],
    correctAnswer: 'ঘ',
    type: 'single',
  },
  {
    id: 'pq-9',
    number: 9,
    question: "'সুভা' গল্পে পিতা-মাতার মনে কে সর্বদাই জাগ্রুক ছিল?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'সুকেশিনী' },
      { label: 'খ', text: 'সুভাষিণী' },
      { label: 'গ', text: 'সুহাসিনী' },
      { label: 'ঘ', text: 'প্রতাপ' },
    ],
    correctAnswer: 'খ',
    type: 'single',
  },
  {
    id: 'pq-10',
    number: 10,
    question: "গদ্যাংশ অনুযায়ী সভা অসহায় সলা আত্মসমর্পণ করতে কার কাছে?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'মায়ের কাছে' },
      { label: 'খ', text: 'বাণীকণ্ঠের কাছে' },
      { label: 'গ', text: 'প্রতাপের কাছে' },
      { label: 'ঘ', text: 'পিতার কাছে' },
    ],
    correctAnswer: 'খ',
    type: 'single',
  },
  {
    id: 'pq-11',
    number: 11,
    question: "'সুভা' গল্পে বাণীকণ্ঠ কে ছিলেন?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'সুভার পিতা' },
      { label: 'খ', text: 'সুভার ভাই' },
      { label: 'গ', text: 'গ্রামের জমিদার' },
      { label: 'ঘ', text: 'সুভার মামা' },
    ],
    correctAnswer: 'ক',
    type: 'single',
  },
  {
    id: 'pq-12',
    number: 12,
    question: "সুভা কথা বলতে পারত না কেন?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'সে বোবা ছিল' },
      { label: 'খ', text: 'সে কথা বলতে চাইত না' },
      { label: 'গ', text: 'সে লাজুক ছিল' },
      { label: 'ঘ', text: 'সে অসুস্থ ছিল' },
    ],
    correctAnswer: 'ক',
    type: 'single',
  },
  {
    id: 'pq-13',
    number: 13,
    question: "'সুভা' গল্পে গ্রামের নাম কী ছিল?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'কালীগঞ্জ' },
      { label: 'খ', text: 'চণ্ডীপুর' },
      { label: 'গ', text: 'নিশ্চিন্দিপুর' },
      { label: 'ঘ', text: 'রামপুর' },
    ],
    correctAnswer: 'খ',
    type: 'single',
  },
  {
    id: 'pq-14',
    number: 14,
    question: "সুভার দুটি গাভীর নাম কী ছিল?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'সর্বশী ও পাঙ্গুলি' },
      { label: 'খ', text: 'লক্ষ্মী ও সরস্বতী' },
      { label: 'গ', text: 'কালী ও দুর্গা' },
      { label: 'ঘ', text: 'মঙ্গলা ও শুভঙ্গী' },
    ],
    correctAnswer: 'ক',
    type: 'single',
  },
  {
    id: 'pq-15',
    number: 15,
    question: "প্রতাপ কী পেশায় নিযুক্ত ছিল?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'কৃষক' },
      { label: 'খ', text: 'মাছ ধরা' },
      { label: 'গ', text: 'ব্যবসায়ী' },
      { label: 'ঘ', text: 'চাকরিজীবী' },
    ],
    correctAnswer: 'খ',
    type: 'single',
  },
  {
    id: 'pq-16',
    number: 16,
    question: "'সুভা' গল্পটি কার লেখা?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'শরৎচন্দ্র চট্টোপাধ্যায়' },
      { label: 'খ', text: 'রবীন্দ্রনাথ ঠাকুর' },
      { label: 'গ', text: 'বঙ্কিমচন্দ্র চট্টোপাধ্যায়' },
      { label: 'ঘ', text: 'মানিক বন্দ্যোপাধ্যায়' },
    ],
    correctAnswer: 'খ',
    type: 'single',
  },
  {
    id: 'pq-17',
    number: 17,
    question: "সুভার বয়স কত ছিল গল্পে?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: '১২ বছর' },
      { label: 'খ', text: '১৪ বছর' },
      { label: 'গ', text: '১৬ বছর' },
      { label: 'ঘ', text: '১৮ বছর' },
    ],
    correctAnswer: 'গ',
    type: 'single',
  },
  {
    id: 'pq-18',
    number: 18,
    question: "সুভার কয়জন বোন ছিল?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'একজন' },
      { label: 'খ', text: 'দুইজন' },
      { label: 'গ', text: 'তিনজন' },
      { label: 'ঘ', text: 'চারজন' },
    ],
    correctAnswer: 'খ',
    type: 'single',
  },
  {
    id: 'pq-19',
    number: 19,
    question: "সুভা নদীর ধারে বসে থাকত কেন?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'মাছ ধরতে' },
      { label: 'খ', text: 'একাকীত্ব উপভোগ করতে' },
      { label: 'গ', text: 'প্রতাপকে দেখতে' },
      { label: 'ঘ', text: 'স্নান করতে' },
    ],
    correctAnswer: 'খ',
    type: 'single',
  },
  {
    id: 'pq-20',
    number: 20,
    question: "গল্পের শেষে সুভাকে কোথায় পাঠানো হয়েছিল?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'কলকাতায়' },
      { label: 'খ', text: 'ঢাকায়' },
      { label: 'গ', text: 'বিদেশে' },
      { label: 'ঘ', text: 'শ্বশুরবাড়িতে' },
    ],
    correctAnswer: 'ক',
    type: 'single',
  },
  {
    id: 'pq-21',
    number: 21,
    question: "'সুভা' গল্পে প্রকৃতির সঙ্গে সুভার সম্পর্ক কেমন ছিল?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'নিবিড়' },
      { label: 'খ', text: 'দূরত্বপূর্ণ' },
      { label: 'গ', text: 'অপরিচিত' },
      { label: 'ঘ', text: 'বিরোধপূর্ণ' },
    ],
    correctAnswer: 'ক',
    type: 'single',
  },
  {
    id: 'pq-22',
    number: 22,
    question: "সুভার মা সুভাকে কী মনে করতেন?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'আশীর্বাদ' },
      { label: 'খ', text: 'গর্বের বিষয়' },
      { label: 'গ', text: 'নিজের দোষ' },
      { label: 'ঘ', text: 'সৌভাগ্য' },
    ],
    correctAnswer: 'গ',
    type: 'single',
  },
  {
    id: 'pq-23',
    number: 23,
    question: "'সুভা' গল্পে নদীর নাম কী ছিল?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'পদ্মা' },
      { label: 'খ', text: 'মেঘনা' },
      { label: 'গ', text: 'যমুনা' },
      { label: 'ঘ', text: 'কোনো নাম নেই' },
    ],
    correctAnswer: 'ঘ',
    type: 'single',
  },
  {
    id: 'pq-24',
    number: 24,
    question: "প্রতাপ সুভার সাথে কী করত?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'গল্প করত' },
      { label: 'খ', text: 'মাছ ধরত' },
      { label: 'গ', text: 'পড়াশোনা করত' },
      { label: 'ঘ', text: 'খেলা করত' },
    ],
    correctAnswer: 'খ',
    type: 'single',
  },
  {
    id: 'pq-25',
    number: 25,
    question: "সুভার চোখের ভাষা কেমন ছিল?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'অস্পষ্ট' },
      { label: 'খ', text: 'সীমিত' },
      { label: 'গ', text: 'অসীম ও গভীর' },
      { label: 'ঘ', text: 'সাধারণ' },
    ],
    correctAnswer: 'গ',
    type: 'single',
  },
  {
    id: 'pq-26',
    number: 26,
    question: "'সুভা' গল্পে বাণীকণ্ঠ কোন সমাজের প্রতিনিধি?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'নিম্নবিত্ত' },
      { label: 'খ', text: 'মধ্যবিত্ত' },
      { label: 'গ', text: 'উচ্চবিত্ত' },
      { label: 'ঘ', text: 'দরিদ্র' },
    ],
    correctAnswer: 'খ',
    type: 'single',
  },
  {
    id: 'pq-27',
    number: 27,
    question: "সুভার বিবাহের ব্যবস্থা কে করেছিলেন?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'মা' },
      { label: 'খ', text: 'বাবা' },
      { label: 'গ', text: 'দুই বোন' },
      { label: 'ঘ', text: 'গ্রামের লোক' },
    ],
    correctAnswer: 'খ',
    type: 'single',
  },
  {
    id: 'pq-28',
    number: 28,
    question: "'সুভা' গল্পের মূল বিষয়বস্তু কী?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'প্রেম' },
      { label: 'খ', text: 'বিচ্ছেদ' },
      { label: 'গ', text: 'প্রতিবন্ধীর যন্ত্রণা' },
      { label: 'ঘ', text: 'গ্রামীণ জীবন' },
    ],
    correctAnswer: 'গ',
    type: 'single',
  },
  {
    id: 'pq-29',
    number: 29,
    question: "সুভার স্বামী কেমন লোক ছিল?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'দয়ালু' },
      { label: 'খ', text: 'নির্দয়' },
      { label: 'গ', text: 'ভালোবাসাপূর্ণ' },
      { label: 'ঘ', text: 'বুদ্ধিমান' },
    ],
    correctAnswer: 'খ',
    type: 'single',
  },
  {
    id: 'pq-30',
    number: 30,
    question: "'সুভা' গল্পটি কোন গল্পগ্রন্থের অন্তর্গত?",
    questionStyle: { fontSize: 14, fontFamily: 'SolaimanLipi', textAlign: 'left' },
    options: [
      { label: 'ক', text: 'গল্পগুচ্ছ' },
      { label: 'খ', text: 'গল্পসল্প' },
      { label: 'গ', text: 'তিনসঙ্গী' },
      { label: 'ঘ', text: 'সে' },
    ],
    correctAnswer: 'ক',
    type: 'single',
  },
];
